# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from .core import Frontmatter
from .core import InvokerFactory
from .core import Prompty

from .renderers import MustacheRenderer
from .parsers import RoleMap
from .parsers import PromptyChatParser
from .utils import load, prepare
from ._patch import patch_sdk as _patch_sdk, get_prompt_config
from ._prompt_config import PromptConfig

InvokerFactory().register_renderer("mustache", MustacheRenderer)
InvokerFactory().register_parser("prompty.chat", PromptyChatParser)

__all__ = [
    "Frontmatter",
    "InvokerFactory",
    "MustacheRenderer",
    "Prompty",
    "PromptyChatParser",
    "RoleMap",
    "load",
    "prepare",
    "get_prompt_config",
    "PromptConfig",
]

_patch_sdk()
